name: Tests Coverage

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**/README.md'
  push:
    branches:
      - master
    paths-ignore:
      - '**/README.md'

env:
  TARPAULIN_VERSION: 0.19.1

jobs:
  test:
    name: Coverage Report
    runs-on: [self-hosted]
    steps:
      - name: Cancel Previous Runs
        # Only cancel non-master branch runs
        if: ${{ github.ref != 'refs/heads/master' }}

        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          toolchain: nightly-2022-10-30
          components: rustfmt
          target: wasm32-unknown-unknown
      - name: Generate code coverage
        run: |
          wget https://github.com/xd009642/tarpaulin/releases/download/${{ env.TARPAULIN_VERSION }}/cargo-tarpaulin-${{ env.TARPAULIN_VERSION }}-travis.tar.gz
          tar -zxvf cargo-tarpaulin-${{ env.TARPAULIN_VERSION }}-travis.tar.gz -C $HOME/.cargo/bin
          make Cargo.toml
          cargo tarpaulin --verbose --no-fail-fast --workspace --timeout 300 --out Xml
      - name: Upload to codecov.io
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true